In [1]:
#total claim ammount is the target

In [2]:
#imports
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression 
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import Ridge, Lasso, ElasticNet


In [3]:
# get the dataframes
categorical_df=pd.read_csv("categorical.csv")
numerical_df=pd.read_csv("numerical.csv")

In [4]:
categorical_df

state response  coverage education employmentstatus gender  \
0     Washington       No     Basic  Bachelor         Employed      F   
1        Arizona       No  Extended  Bachelor       Unemployed      F   
2         Nevada       No   Premium  Bachelor         Employed      F   
3     California       No     Basic  Bachelor       Unemployed      M   
4     Washington       No     Basic  Bachelor         Employed      M   
...          ...      ...       ...       ...              ...    ...   
9129  California       No     Basic  Bachelor         Employed      M   
9130  California      Yes  Extended   College         Employed      F   
9131  California       No  Extended  Bachelor       Unemployed      M   
9132  California       No  Extended   College         Employed      M   
9133  California       No  Extended   College       Unemployed      M   

     location_code marital_status     policy_type renew_offer_type  \
0         Suburban        Married  Corporate Auto           Offer1   
1         Suburban         Single   Personal Auto           Offer3   
2         Suburban        Married   Personal Auto           Offer1   
3         Suburban        Married  Corporate Auto           Offer1   
4            Rural         Single   Personal Auto           Offer1   
...            ...            ...             ...              ...   
9129         Urban        Married   Personal Auto           Offer2   
9130      Suburban       Divorced  Corporate Auto           Offer1   
9131      Suburban         Single  Corporate Auto           Offer1   
9132      Suburban        Married   Personal Auto           Offer3   
9133      Suburban         Single  Corporate Auto           Offer4   

     sales_channel  vehicle_class vehicle_size  policy_level  
0            Agent   Two-Door Car      Medsize             3  
1            Agent  Four-Door Car      Medsize             3  
2            Agent   Two-Door Car      Medsize             3  
3      Call Center            SUV      Medsize             2  
4            Agent  Four-Door Car      Medsize             1  
...            ...            ...          ...           ...  
9129           Web  Four-Door Car      Medsize             1  
9130        Branch  Four-Door Car      Medsize             3  
9131        Branch  Four-Door Car      Medsize             2  
9132        Branch  Four-Door Car        Large             2  
9133   Call Center   Two-Door Car      Medsize             3  

[9134 rows x 14 columns]

In [5]:
# concat the 2 dataframes
data =pd.concat([categorical_df,numerical_df],axis=1)
data

state response  coverage education employmentstatus gender  \
0     Washington       No     Basic  Bachelor         Employed      F   
1        Arizona       No  Extended  Bachelor       Unemployed      F   
2         Nevada       No   Premium  Bachelor         Employed      F   
3     California       No     Basic  Bachelor       Unemployed      M   
4     Washington       No     Basic  Bachelor         Employed      M   
...          ...      ...       ...       ...              ...    ...   
9129  California       No     Basic  Bachelor         Employed      M   
9130  California      Yes  Extended   College         Employed      F   
9131  California       No  Extended  Bachelor       Unemployed      M   
9132  California       No  Extended   College         Employed      M   
9133  California       No  Extended   College       Unemployed      M   

     location_code marital_status     policy_type renew_offer_type  ...  \
0         Suburban        Married  Corporate Auto           Offer1  ...   
1         Suburban         Single   Personal Auto           Offer3  ...   
2         Suburban        Married   Personal Auto           Offer1  ...   
3         Suburban        Married  Corporate Auto           Offer1  ...   
4            Rural         Single   Personal Auto           Offer1  ...   
...            ...            ...             ...              ...  ...   
9129         Urban        Married   Personal Auto           Offer2  ...   
9130      Suburban       Divorced  Corporate Auto           Offer1  ...   
9131      Suburban         Single  Corporate Auto           Offer1  ...   
9132      Suburban        Married   Personal Auto           Offer3  ...   
9133      Suburban         Single  Corporate Auto           Offer4  ...   

     vehicle_size policy_level customer_lifetime_value   income  \
0         Medsize            3             2763.519279  56274.0   
1         Medsize            3             6979.535903      0.0   
2         Medsize            3            12887.431650  48767.0   
3         Medsize            2             7645.861827      0.0   
4         Medsize            1             2813.692575  43836.0   
...           ...          ...                     ...      ...   
9129      Medsize            1                     NaN      NaN   
9130      Medsize            3                     NaN      NaN   
9131      Medsize            2                     NaN      NaN   
9132        Large            2                     NaN      NaN   
9133      Medsize            3                     NaN      NaN   

      monthly_premium_auto  months_since_last_claim  \
0                     69.0                     32.0   
1                     94.0                     13.0   
2                    108.0                     18.0   
3                    106.0                     18.0   
4                     73.0                     12.0   
...                    ...                      ...   
9129                   NaN                      NaN   
9130                   NaN                      NaN   
9131                   NaN                      NaN   
9132                   NaN                      NaN   
9133                   NaN                      NaN   

      months_since_policy_inception  total_claim_amount  \
0                               5.0          384.811147   
1                              42.0         1131.464935   
2                              38.0          566.472247   
3                              65.0          529.881344   
4                              44.0          138.130879   
...                             ...                 ...   
9129                            NaN                 NaN   
9130                            NaN                 NaN   
9131                            NaN                 NaN   
9132                            NaN                 NaN   
9133                            NaN                 NaN   

      number_of_open_complaints  number_of_policies  
0   

In [6]:
data.isna().sum()

state                              0
response                           0
coverage                           0
education                          0
employmentstatus                   0
gender                             0
location_code                      0
marital_status                     0
policy_type                        0
renew_offer_type                   0
sales_channel                      0
vehicle_class                      0
vehicle_size                       0
policy_level                       0
customer_lifetime_value          430
income                           430
monthly_premium_auto             430
months_since_last_claim          430
months_since_policy_inception    430
total_claim_amount               430
number_of_open_complaints        430
number_of_policies               430
dtype: int64

In [7]:
data=data.dropna()
data

state response  coverage             education employmentstatus  \
0     Washington       No     Basic              Bachelor         Employed   
1        Arizona       No  Extended              Bachelor       Unemployed   
2         Nevada       No   Premium              Bachelor         Employed   
3     California       No     Basic              Bachelor       Unemployed   
4     Washington       No     Basic              Bachelor         Employed   
...          ...      ...       ...                   ...              ...   
8699  California      Yes     Basic              Bachelor         Employed   
8700  California       No     Basic               College         Employed   
8701  California       No  Extended  High School or Below       Unemployed   
8702  California       No  Extended  High School or Below         Employed   
8703  California       No  Extended               College       Unemployed   

     gender location_code marital_status     policy_type renew_offer_type  \
0         F      Suburban        Married  Corporate Auto           Offer1   
1         F      Suburban         Single   Personal Auto           Offer3   
2         F      Suburban        Married   Personal Auto           Offer1   
3         M      Suburban        Married  Corporate Auto           Offer1   
4         M         Rural         Single   Personal Auto           Offer1   
...     ...           ...            ...             ...              ...   
8699      F         Rural        Married   Personal Auto           Offer2   
8700      M         Urban        Married  Corporate Auto           Offer1   
8701      F      Suburban         Single  Corporate Auto           Offer1   
8702      F         Urban        Married   Personal Auto           Offer1   
8703      M      Suburban        Married  Corporate Auto           Offer3   

      ... vehicle_size policy_level customer_lifetime_value   income  \
0     ...      Medsize            3             2763.519279  56274.0   
1     ...      Medsize            3             6979.535903      0.0   
2     ...      Medsize            3            12887.431650  48767.0   
3     ...      Medsize            2             7645.861827      0.0   
4     ...      Medsize            1             2813.692575  43836.0   
...   ...          ...          ...                     ...      ...   
8699  ...      Medsize            1            23405.987980  71941.0   
8700  ...      Medsize            3             3096.511217  21604.0   
8701  ...      Medsize            2             8163.890428      0.0   
8702  ...      Medsize            2             7524.442436  21941.0   
8703  ...      Medsize            3             2611.836866      0.0   

      monthly_premium_auto  months_since_last_claim  \
0                     69.0                     32.0   
1                     94.0                     13.0   
2                    108.0                     18.0   
3                    106.0                     18.0   
4                     73.0                     12.0   
...                    ...                      ...   
8699                  73.0                     18.0   
8700                  79.0                     14.0   
8701                  85.0                      9.0   
8702                  96.0                     34.0   
8703                  77.0                      3.0   

      months_since_policy_inception  total_claim_amount  \
0                               5.0          384.811147   
1                              42.0         1131.464935   
2                              38.0          566.472247   
3                              65.0          529.881344   
4                              44.0          138.130879   
...                             ...                 ...   
8699                           89.0          198.234764   
8700                           28.0          379.200000   
8701                           37.0          790.784983   
8702                            3

In [8]:
X=data.drop("total_claim_amount",axis=1)
y=data["total_claim_amount"]

In [9]:
# training test splits
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
#normalize categorical data
X_train_num = X_train.select_dtypes(include = np.number)

# Scaling data
transformer = MinMaxScaler().fit(X_train_num) # need to keep transformer
X_train_normalized = transformer.transform(X_train_num)
X_train_norm = pd.DataFrame(X_train_normalized)
X_train_norm

0         1         2         3         4         5    6      7
0     1.0  0.085854  0.471460  0.211009  0.142857  0.111111  0.8  0.000
1     1.0  0.138153  0.845551  0.532110  0.285714  0.717172  0.0  0.125
2     1.0  0.072330  0.230954  0.321101  0.800000  0.909091  0.0  0.500
3     0.5  0.117385  0.877447  0.082569  0.685714  0.656566  0.0  0.125
4     0.5  0.141995  0.000000  0.275229  0.942857  0.383838  0.0  0.125
...   ...       ...       ...       ...       ...       ...  ...    ...
6958  1.0  0.082305  0.306948  0.183486  0.657143  0.515152  0.0  0.500
6959  0.0  0.047042  0.000000  0.000000  0.200000  0.010101  0.0  0.625
6960  1.0  0.160098  0.310689  0.284404  0.571429  0.191919  0.0  0.000
6961  1.0  0.578714  0.518499  0.302752  0.285714  0.757576  0.0  0.875
6962  0.5  0.543735  0.190696  0.385321  0.142857  0.616162  0.4  0.125

[6963 rows x 8 columns]

### Encode categoricals


In [11]:
#i will first split them into nominal and ordinal
X_train_cat_ordinal = X_train[["coverage","education","vehicle_size","policy_level"]]
X_train_cat_nominal = X_train[['state', 'response',"employmentstatus", 'gender', 'location_code','marital_status', 'policy_type', 'renew_offer_type', 'sales_channel','vehicle_class']]

X_train_cat_ordinal

coverage             education vehicle_size  policy_level
7135     Basic               College        Small             3
5748  Extended              Bachelor      Medsize             3
6887  Extended                Doctor      Medsize             3
6208     Basic              Bachelor      Medsize             2
2298     Basic  High School or Below      Medsize             2
...        ...                   ...          ...           ...
490      Basic  High School or Below      Medsize             3
7330     Basic              Bachelor      Medsize             1
963      Basic  High School or Below        Small             3
5376   Premium                Master      Medsize             3
6665     Basic  High School or Below        Large             2

[6963 rows x 4 columns]

In [12]:
# one hot encode nominals 
nominal_encoder = OneHotEncoder(drop="first").fit(X_train_cat_nominal)
encoded_nominals=nominal_encoder.transform(X_train_cat_nominal).toarray()
encoded_nominals

array([[0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
#put the ordinals in order
coverage_order = ['Basic', 'Extended', 'Premium']
education_order = ['High School or Below', 'College', 'Bachelor', 'Master', 'Doctor']
vehicle_size_order = ['Small', 'Medsize', 'Large']
policy_level_order = [1, 2, 3]  

In [14]:
# creating the encoder for the ordinal encoding with the categories
ordinal_encoder = OrdinalEncoder(categories=[coverage_order, education_order, vehicle_size_order, policy_level_order])

In [15]:
# apply it 
encoded_ordinals= ordinal_encoder.fit_transform(X_train_cat_ordinal)
encoded_ordinals

array([[0., 1., 0., 2.],
       [1., 2., 1., 2.],
       [1., 4., 1., 2.],
       ...,
       [0., 0., 0., 2.],
       [2., 3., 1., 2.],
       [0., 0., 2., 1.]])

In [16]:
# put categoricals together again
encoded_categoricals_train = np.concatenate((encoded_ordinals, encoded_nominals), axis=1)
encoded_categoricals_train


array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 2., 1., ..., 0., 1., 0.],
       [1., 4., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [2., 3., 1., ..., 0., 1., 0.],
       [0., 0., 2., ..., 0., 0., 0.]])

In [17]:
#put numerical and categorical TRAIN data together
X_train_transformed = np.concatenate([encoded_categoricals_train,X_train_norm],axis=1)
X_train_transformed

array([[0.        , 1.        , 0.        , ..., 0.11111111, 0.8       ,
        0.        ],
       [1.        , 2.        , 1.        , ..., 0.71717172, 0.        ,
        0.125     ],
       [1.        , 4.        , 1.        , ..., 0.90909091, 0.        ,
        0.5       ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.19191919, 0.        ,
        0.        ],
       [2.        , 3.        , 1.        , ..., 0.75757576, 0.        ,
        0.875     ],
       [0.        , 0.        , 2.        , ..., 0.61616162, 0.4       ,
        0.125     ]])

In [18]:
X_train_trasnformed_df = pd.DataFrame(X_train_transformed)
X_train_trasnformed_df

0    1    2    3    4    5    6    7    8    9   ...   24   25   26  \
0     0.0  1.0  0.0  2.0  0.0  0.0  1.0  0.0  1.0  1.0  ...  0.0  0.0  1.0   
1     1.0  2.0  1.0  2.0  1.0  0.0  0.0  0.0  1.0  1.0  ...  1.0  0.0  1.0   
2     1.0  4.0  1.0  2.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  1.0   
3     0.0  2.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.5   
4     0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.5   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
6958  0.0  0.0  1.0  2.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
6959  0.0  2.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6960  0.0  0.0  0.0  2.0  0.0  0.0  1.0  0.0  0.0  1.0  ...  0.0  0.0  1.0   
6961  2.0  3.0  1.0  2.0  0.0  0.0  1.0  0.0  1.0  1.0  ...  1.0  0.0  1.0   
6962  0.0  0.0  2.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  0.0  0.5   

            27        28        29        30        31   32     33  
0     0.085854  0.471460  0.211009  0.142857  0.111111  0.8  0.000  
1     0.138153  0.845551  0.532110  0.285714  0.717172  0.0  0.125  
2     0.072330  0.230954  0.321101  0.800000  0.909091  0.0  0.500  
3     0.117385  0.877447  0.082569  0.685714  0.656566  0.0  0.125  
4     0.141995  0.000000  0.275229  0.942857  0.383838  0.0  0.125  
...        ...       ...       ...       ...       ...  ...    ...  
6958  0.082305  0.306948  0.183486  0.657143  0.515152  0.0  0.500  
6959  0.047042  0.000000  0.000000  0.200000  0.010101  0.0  0.625  
6960  0.160098  0.310689  0.284404  0.571429  0.191919  0.0  0.000  
6961  0.578714  0.518499  0.302752  0.285714  0.757576  0.0  0.875  
6962  0.543735  0.190696  0.385321  0.142857  0.616162  0.4  0.125  

[6963 rows x 34 columns]

### # now to transform the test data


In [19]:
# now we are transforming our numerical TEST data
# for numericals
X_test_num = X_test.select_dtypes(include = np.number)

# Scaling data
# we use the transformer that was trained on the training data
X_test_normalized = transformer.transform(X_test_num)
X_test_norm = pd.DataFrame(X_test_normalized,columns = X_test_num.columns)
X_test_norm.head()

policy_level  customer_lifetime_value    income  monthly_premium_auto  \
0           0.5                 0.055381  0.000000              0.082569   
1           0.5                 0.015126  0.451996              0.073394   
2           1.0                 0.342094  0.305408              0.045872   
3           1.0                 0.052466  0.000000              0.688073   
4           1.0                 0.085296  0.000000              0.036697   

   months_since_last_claim  months_since_policy_inception  \
0                 0.714286                       0.484848   
1                 0.514286                       0.343434   
2                 0.628571                       0.181818   
3                 0.800000                       0.878788   
4                 0.971429                       0.272727   

   number_of_open_complaints  number_of_policies  
0                        0.0               0.625  
1                        0.0               0.000  
2                        0.0               0.750  
3                        0.4               0.250  
4                        0.0               0.000

In [20]:
# now to transform the test data
X_test_num = X_test.select_dtypes(include = np.number)

# Scaling data
# we use the transformer that was trained on the training data
X_test_normalized = transformer.transform(X_test_num)
X_test_norm = pd.DataFrame(X_test_normalized,columns = X_test_num.columns)
X_test_norm

policy_level  customer_lifetime_value    income  monthly_premium_auto  \
0              0.5                 0.055381  0.000000              0.082569   
1              0.5                 0.015126  0.451996              0.073394   
2              1.0                 0.342094  0.305408              0.045872   
3              1.0                 0.052466  0.000000              0.688073   
4              1.0                 0.085296  0.000000              0.036697   
...            ...                      ...       ...                   ...   
1736           0.5                 0.010078  0.409898              0.009174   
1737           0.0                 0.058648  0.434693              0.027523   
1738           0.0                 0.039295  0.285114              0.394495   
1739           0.5                 0.009373  0.000000              0.055046   
1740           1.0                 0.100647  0.388814              0.302752   

      months_since_last_claim  months_since_policy_inception  \
0                    0.714286                       0.484848   
1                    0.514286                       0.343434   
2                    0.628571                       0.181818   
3                    0.800000                       0.878788   
4                    0.971429                       0.272727   
...                       ...                            ...   
1736                 0.171429                       0.888889   
1737                 0.685714                       0.474747   
1738                 0.771429                       0.373737   
1739                 0.085714                       0.424242   
1740                 0.171429                       0.868687   

      number_of_open_complaints  number_of_policies  
0                           0.0               0.625  
1                           0.0               0.000  
2                           0.0               0.750  
3                           0.4               0.250  
4                           0.0               0.000  
...                         ...                 ...  
1736                        0.0               0.125  
1737                        0.0               0.000  
1738                        0.0               0.000  
1739                        0.0               0.000  
1740                        0.2               0.875  

[1741 rows x 8 columns]

In [21]:
#encode categoricals ,again spliting ordinals and nominals
#i will first split them into nominal and ordinal
X_test_cat_ordinal = X_test[["coverage", "education", "vehicle_size", "policy_level"]]
X_test_cat_nominal = X_test[['state', 'response', "employmentstatus", 'gender', 'location_code', 'marital_status', 'policy_type', 'renew_offer_type', 'sales_channel', 'vehicle_class']]

In [22]:
#nominals
encoded_nominals_test=nominal_encoder.transform(X_test_cat_nominal).toarray()
encoded_nominals_test

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [23]:
#ordinals 
encoded_ordinals_test= ordinal_encoder.fit_transform(X_test_cat_ordinal)
encoded_ordinals_test

array([[1., 1., 0., 1.],
       [0., 0., 2., 1.],
       [0., 2., 1., 2.],
       ...,
       [1., 3., 0., 0.],
       [2., 1., 1., 1.],
       [0., 4., 1., 2.]])

In [24]:
# put categoricals together again
encoded_categoricals_test = np.concatenate((encoded_ordinals_test, encoded_nominals_test), axis=1)
encoded_categoricals_test


array([[1., 1., 0., ..., 0., 1., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       [0., 2., 1., ..., 1., 0., 0.],
       ...,
       [1., 3., 0., ..., 0., 0., 0.],
       [2., 1., 1., ..., 1., 0., 0.],
       [0., 4., 1., ..., 1., 0., 0.]])

In [25]:
# put everything togeteher 
X_test_transformed = np.concatenate([encoded_categoricals_test,X_test_norm],axis=1)
X_test_transformed

array([[1.        , 1.        , 0.        , ..., 0.48484848, 0.        ,
        0.625     ],
       [0.        , 0.        , 2.        , ..., 0.34343434, 0.        ,
        0.        ],
       [0.        , 2.        , 1.        , ..., 0.18181818, 0.        ,
        0.75      ],
       ...,
       [1.        , 3.        , 0.        , ..., 0.37373737, 0.        ,
        0.        ],
       [2.        , 1.        , 1.        , ..., 0.42424242, 0.        ,
        0.        ],
       [0.        , 4.        , 1.        , ..., 0.86868687, 0.2       ,
        0.875     ]])

In [26]:
X_test_trasnformed_df = pd.DataFrame(X_test_transformed)
X_test_trasnformed_df

0    1    2    3    4    5    6    7    8    9   ...   24   25   26  \
0     1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  ...  1.0  0.0  0.5   
1     0.0  0.0  2.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.5   
2     0.0  2.0  1.0  2.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  1.0   
3     0.0  0.0  1.0  2.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  0.0  1.0   
4     1.0  4.0  1.0  2.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  1.0  0.0  1.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1736  0.0  3.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  ...  0.0  1.0  0.5   
1737  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1738  1.0  3.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
1739  2.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.5   
1740  0.0  4.0  1.0  2.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  1.0   

            27        28        29        30        31   32     33  
0     0.055381  0.000000  0.082569  0.714286  0.484848  0.0  0.625  
1     0.015126  0.451996  0.073394  0.514286  0.343434  0.0  0.000  
2     0.342094  0.305408  0.045872  0.628571  0.181818  0.0  0.750  
3     0.052466  0.000000  0.688073  0.800000  0.878788  0.4  0.250  
4     0.085296  0.000000  0.036697  0.971429  0.272727  0.0  0.000  
...        ...       ...       ...       ...       ...  ...    ...  
1736  0.010078  0.409898  0.009174  0.171429  0.888889  0.0  0.125  
1737  0.058648  0.434693  0.027523  0.685714  0.474747  0.0  0.000  
1738  0.039295  0.285114  0.394495  0.771429  0.373737  0.0  0.000  
1739  0.009373  0.000000  0.055046  0.085714  0.424242  0.0  0.000  
1740  0.100647  0.388814  0.302752  0.171429  0.868687  0.2  0.875  

[1741 rows x 34 columns]

### cleaning and transforming done ,lets go with the models
6. Try a simple linear regression with all the data to see whether we are getting good results.

In [27]:
lm=linear_model.LinearRegression()
lm.fit(X_train_transformed,y_train)

LinearRegression()

In [28]:
predictions_test = lm.predict(X_test_transformed)
predictions_test

array([422.2466315 , 290.02242824, 308.51144061, ..., 523.89817852,
       443.35864972, 433.87856481])

In [29]:
def evaluate_regression(y_test, predictions_test):
    mse = mean_squared_error(y_test, predictions_test)
    rmse = mean_squared_error(y_test, predictions_test, squared=False)
    mae = mean_absolute_error(y_test, predictions_test)
    r2 = r2_score(y_test, predictions_test)
    
    return mse, rmse, mae, r2

mse, rmse, mae, r2 = evaluate_regression(y_test, predictions_test)
print(f"MSE: {mse}, RMSE: {rmse}, MAE: {mae}, R2: {r2}")

MSE: 34488.63593749187, RMSE: 185.71116266259244, MAE: 135.58332082227207, R2: 0.3896121380373132


In [30]:
#not bad ,that seems to be a decente R2 

### 7.Great! Now define a function that takes a list of models and train (and tests) them so we can try a lot of them without repeating code.

In [31]:
def test_models(X_train,X_test,y_train,y_test,models=None):
    if models is None:
        models = {
            'Linear Regression': LinearRegression(),
            'KNN': KNeighborsRegressor(),
            'MLP Regressor': MLPRegressor(max_iter=10000),
            'Random Forest': RandomForestRegressor(),
            'Gradient Boosting': GradientBoostingRegressor(),
            'SVR': SVR(),
            'Decision Tree': DecisionTreeRegressor(),
            'Ridge': Ridge(),
            'Lasso': Lasso(),
            'Elastic Net': ElasticNet()
        }
    
    results= {}
    
    for name,model in models.items():
        model.fit(X_train,y_train)    #train the model
        predictions=model.predict(X_test) #prdict on the test set
        
        mse = mean_squared_error(y_test,predictions) # Mean Squared Error
        r2 = r2_score(y_test,predictions) # R2
        
        results[name] = {"MSE":mse, "R2": r2}
        
    return results

In [32]:
results = test_models(X_train_transformed,X_test_transformed,y_train,y_test)

In [33]:
results

{'Linear Regression': {'MSE': 34488.63593749187, 'R2': 0.3896121380373132},
 'KNN': {'MSE': 57057.169465072475, 'R2': -0.009810992309167599},
 'MLP Regressor': {'MSE': 34790.90876081457, 'R2': 0.38426244364256334},
 'Random Forest': {'MSE': 30002.129813578846, 'R2': 0.4690153619172347},
 'Gradient Boosting': {'MSE': 31398.007847960245, 'R2': 0.4443107893585816},
 'SVR': {'MSE': 54013.35534452367, 'R2': 0.04405913455293686},
 'Decision Tree': {'MSE': 59687.779468247805, 'R2': -0.05636813705696353},
 'Ridge': {'MSE': 34491.67794184976, 'R2': 0.3895582999400494},
 'Lasso': {'MSE': 34438.05047882778, 'R2': 0.390507411193849},
 'Elastic Net': {'MSE': 51946.95836543894, 'R2': 0.08063070660106608}}

In [34]:
sorted_results = sorted(results.items(), key=lambda x: x[1]['R2'], reverse=True)
sorted_results

[('Random Forest', {'MSE': 30002.129813578846, 'R2': 0.4690153619172347}),
 ('Gradient Boosting', {'MSE': 31398.007847960245, 'R2': 0.4443107893585816}),
 ('Lasso', {'MSE': 34438.05047882778, 'R2': 0.390507411193849}),
 ('Linear Regression', {'MSE': 34488.63593749187, 'R2': 0.3896121380373132}),
 ('Ridge', {'MSE': 34491.67794184976, 'R2': 0.3895582999400494}),
 ('MLP Regressor', {'MSE': 34790.90876081457, 'R2': 0.38426244364256334}),
 ('Elastic Net', {'MSE': 51946.95836543894, 'R2': 0.08063070660106608}),
 ('SVR', {'MSE': 54013.35534452367, 'R2': 0.04405913455293686}),
 ('KNN', {'MSE': 57057.169465072475, 'R2': -0.009810992309167599}),
 ('Decision Tree', {'MSE': 59687.779468247805, 'R2': -0.05636813705696353})]

## 10. Check and discuss the results.

First is first i dont know how all the models work,i just tried to put them in there because they are all supoused to use tha same arguments,and voila,ir right,we got a good bunch of models out of nowhere re using the cleaning code.

After that we can see that the top performers are random forest and gradient boosting,those are espcially good with non linear relationships in the data.

MLP Regressor is a type of neural network.That indicates that there is complex pattern in the data which a neural network can capture.

We got then our old friend Lienar model:Lasso,ridge and linear regresion.
And to talk of the lowest performance ,KNN ,maybe because not touching on the paramenteres,too high dimensionality of the data after encoding ,also know as curse of dimensionality.

But i wont stop here, i will try to check new parameters for some of them to see if i can get a better R2 that 0.46